### ISSUE TITLE
Question about using LSTM model in watch_phone_pocket version

### ISSUE THREAD

**Issue by EndeavoringYoon** [wearable-motion-capture/arm-pose-estimation#30]
Hi, I've read your paper in IROS 2023, and I thought it would be great to apply this method in tele-operating robots. I'm glad that your paper including further developed thesis has been submitted to ICRA 2024, and I'll read it.

Thanks for the kind and well-written code you've provided. I'm working with the watch_phone_pocket version since my watch cannot connect to the UDP socket in the watch_only version. I'm dealing with it.

What I'm wondering about is why there's no results.json for the WatchPhonePocketNN class. I found out that there's a checkpoint for watch_phone_pocket, a variable WATCH_PHONE_POCKET = "7ffa..." in deploy_models.py, and a WatchPhonePocketNN() class in watch_phone_pocket_nn.py.
But despite these data and structures, the main code in watch_phone_pocket.py uses the WatchPhonePocketKalman() class. Without the results.json file, I realized that I cannot load this model because the load_deployed_model_from_hash() function in models.py requires the results.json file.

Is there any reason for this? Does using the Kalman filter perform better than the LSTM model?

**Comment by faweigend** [comment]
Hi, thanks so much for reaching out and sorry for the delayed reply.

- **Re watch_only and UDP:** You have probably considered this but I'll just put this here in case. If the watch is connected to any phone via bluetooth, the phone somehow blocks the UDP messages. I could only connect to the watch when it is really fully by itself, without a phone connected in any way.

- **Re results.json for WatchPhonePocketNN** Thanks for pointing this out. There should definitely be a results.json in the "7ffa..." folder. I'm currently out of office for ICRA24. As soon as I'm back, I will submit the json.

- **Re phone_pocket with Kalman** The structures for the WatchPhonePocketNN are in place for legacy reasons and we found that the Kalman model performs much better. This is actually the story of our [ICRA paper ](https://arxiv.org/abs/2403.07199) and I recommend sticking to the script that uses the Kalman model. Loading the Kalman model does not require a results.json because it is structurally so different. It has its own class.

I will be back in June and make sure to provide the legacy pocket LSTM that you can load with the load_deployed_model_from_hash() method.  Let me know if there are more questions or any other issues!

**Comment by EndeavoringYoon** [comment]
Thanks for your kind reply.

For watch_only and UDP, I found out that there was a problem with my WiFi, so I solved that problem. Now watch_only.py is working very well. I confirmed that the performance of the Kalman model is also good, and I have had some success in controlling the robot using the results from watch_phone_pocket.py.
It is very interesting that the Kalman model performs better than the LSTM, which could become the story for the ICRA paper. I will read the ICRA paper, and I hope to hear good news in June.

Once again, thank you for your kind reply.

**Comment by faweigend** [comment]
Hi EndeavoringYoon,

Just writing to let you know that I updated the legacy LSTM script and you should be able to compare the Kalman and LSTM approach yourself if you would like to.

You can test the LSTM with this script [watch_phone_pocket_lstm.py](https://github.com/wearable-motion-capture/arm-pose-estimation/blob/main/experimental_applications/watch_phone_pocket_lstm.py)

**Comment by EndeavoringYoon** [comment]
Thank you so much for uploading the file and for personally notifying me. I really appreciate your kindness and timely assistance.

I'll check the file and let you know if I have any further questions.
Thanks again for your support!
